version: '3.3'
networks:
  crawler-net:
    driver: bridge
    attachable: true
services:
    database:
      container_name: postgres-db
      image: postgres:13.0-alpine
      restart: always
      env_file:
        - ./.env
      ports:
       - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
      networks:
        crawler-net:
          aliases:
            - crawler-database

    api:
        container_name: api
        build: .
        restart: always
        # command: uwsgi --ini uwsgi.ini
        command:
            - /bin/sh
            - -c
            - |
              python manage.py collectstatic --noinput
              python manage.py makemigrations
              python manage.py migrate
              python manage.py runserver 0.0.0.0:8000
        env_file:
          - ./.env
        ports:
          - "8000:8000"
        volumes:
          - ./:/api
        depends_on:
          - database
        networks:
          crawler-net:
            aliases:
              - crawler-api

volumes:
    pgdata:
