# Generated by Django 4.2.7 on 2023-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('area', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('bedrooms', models.IntegerField(default=0, null=True)),
                ('furniture', models.CharField(max_length=50, null=True)),
                ('bancony', models.CharField(max_length=50, null=True)),
                ('direction', models.CharField(max_length=30, null=True)),
                ('bathrooms', models.IntegerField(default=0, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
