# Generated by Django 4.2.7 on 2023-11-29 18:40

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="images",
            field=ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
